[workspace]
authors = ["Scott Henderson <3924836+scottyhq@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "catalog"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
geopandas = ">=1.1.2,<2"
obspy = ">=1.4.2,<2"
requests = ">=2.32.5,<3"
ipykernel = ">=7.1.0,<8"
